import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: 'swap'
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})



export const metadata: Metadata = {
  title: "DebtBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />

        
      </head>
      <body
        className={`${inter.variable} ${roboto.variable} antialiased`}
      >
        <div className="flex min-h-screen font-main">
          <Sidebar/>
          <main className="flex-1 bg-gray-100 p-6">
            {children}
          </main>
        </div>
        
      </body>
    </html>
  );
}
